language: java
dist: xenial

script:
  - cd scripts
  - ./build-linux32.sh
  - ./build-linux64.sh
  - ./build-macosx.sh
  - cd ..

before_deploy:
  - cd bin
  - tar czf linux32.tar.gz linux-i586/
  - tar czf linux64.tar.gz linux-amd64/
  - tar czf macosx.tar.gz macosx/

deploy:
  provider: releases
  api_key:
    secure: Q9VNV+QOi336zVEVNFnwGs7F2BoKJQaZb14JX0VV9V1/UPbQD/ZXMGBNf3RIpmJeiVD9gQ4Ej71qy05T5MgXoqpe3eL5aD4ywZmsInhEDrR6LW/YOvR5nddfb3C9N3YMU7qnGZ3FKlRd9P+RqmtsS8e+D7HmGq18F/nnmYvbsuM=
  file:
    - linux32.tar.gz
    - linux64.tar.gz
    - macosx.tar.gz
  skip_cleanup: true
  on:
    tags: true
